Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -23,6 +23,6 @@ jobs:
         node-version: ${{ matrix.node-version }}
     - name: Run test
       run: |
-        ret=$(echo `find . -name "*.js" -exec sh -c 'node --check {}; if [ $? -eq 0 ]; then echo PASS {} $'\n'; else echo FAIL {} $'\n'; fi;' \; ;`;)
+        ret=$(echo `find . -name "*.js" -exec sh -c 'node --check {}; if [ $? -eq 0 ]; then echo PASS; else echo FAIL; fi;' \; ;`;)
         echo $ret
         if [[ $ret == *"FAIL"* ]]; then exit 1; fi;
